name: Version Module
run-name: Version Module <${{ github.ref_name }}>

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  gitversion:
    name: Add Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1.1.1
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: version_step
        uses: gittools/actions/gitversion/execute@v1.1.1
        with:
          useConfigFile: true
          configFilePath: 'GitVersion.yaml'
      
      - name: Commit Version
        run: |
          # Fetch the version number from the output of the 'Determine Version' step
          version=${{ steps.version_step.outputs.semVer }}

          # Configure git
          git config --global user.email "github-action@github.com"
          git config --global user.name "GitHub Actions"

          # Create a new tag with the version number
          git tag $version

          # Push the new tag to the remote repository
          git push --tags